name: “Fetch Security News”

on:
  schedule:
    # every 15 minutes
    - cron:  '*/15 * * * *'
  workflow_dispatch:  # manual trigger

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run news-to-discord script
        env:
          NEWSAPI_KEY:       ${{ secrets.NEWSAPI_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python news_to_discord.py
